### ISSUE TITLE
Pull Up resistor 

### ISSUE THREAD

**Issue by T-jakel** [Rat-Rig/V-CoreOS#136]
### What happened

The error occurred when I tried to use the Max 31865 as a wit an pt 1000 thermistor for the hotend  in the printer cfg 

### What did you expect to happen

Ratos 2.1 Error:
The error message "pullup resistor is Not a vailet Funktion" suggests an issue with the pullup resistor configuration in Klipper for Ratos 2.1. wen i remove my max 31865 Option the Error is gone 

### How to reproduce

Simply change the sensor type to max 31865 in the printercfg. Then the error message pullup resistor __ appears immediately.

**Comment by miklschmidt** [comment]
@T-jakel The Max31685 isn't currently supported in RatOS, usually it causes more trouble for the average user than it's worth. Unless you're using a PT100 you don't benefit much from it.

If you want to use one anyway, pick any other thermistor than "PT1000" in the configurator and klipper will stop complaining when you change the sensor_type in printer.cfg since RatOS won't emit the PT1000 specific pullup resistor option :)
