### ISSUE TITLE
variable_adaptive_mesh probes only 3x3?

### ISSUE THREAD

**Issue by MayorBug** [Rat-Rig/V-CoreOS#95]
### What happened

I enabled `variable_adaptive_mesh` and can't get the probe count to be bigger than 3x3

### What did you expect to happen

`variable_adaptive_mesh` to keep resolution when `probe_count` is set

### How to reproduce

`variable_adaptive_mesh`

**Comment by miklschmidt** [comment]
Like PAM, adaptive mesh keeps the resolution of your mesh setup, ie. if you have a 100mmx100mm full mesh with 10 points, it will use 1 point per 10mm. (100/10). Thus anything less than a 30x30mm print will use 3x3 points because 3x3 points is the minimum allowed by klipper. Likewise a 50mmx50mm print would use 5x5 points. If you want to increase the resolution, increase the `probe_count` in `[bed_mesh]`. see: https://www.klipper3d.org/Config_Reference.html#bed_mesh

The default probe_count in RatOS is 7,7.
